### ISSUE TITLE
Please reopen #10

### ISSUE THREAD

**Issue by rosskevin** [arturictus/sidekiq_alive#14]
...and close this one.  From my comment there:

This should be reopened (verified on 1.0.1):

> Throughput of the Redis database indicated below is 1553 RPS (requests per second).

This is a brand new cluster/business with essentially no traffic other than alpha users.  The spike occurs on a new deployment (old one deleted, new one added)

![redis_labs](https://user-images.githubusercontent.com/136564/51492124-4b688c00-1d76-11e9-8a49-b71c09e61fe3.png)

What information could I provide that can help?

**Comment by arturictus** [comment]
hi @rosskevin,
Do you run `quiet` before the pods are stopped?
https://github.com/arturictus/sidekiq_alive#kubernetes-setup

To avoid that I just added a sidekiq middleware on quiet that removes the registered instance from redis. The worker checks if the instance is registered and if not returns without doing nothing.
https://github.com/arturictus/sidekiq_alive/blob/master/lib/sidekiq_alive.rb#L23

**Comment by rosskevin** [comment]
Yes, I am running `quiet` in the lifecycle.  

It seems kubernetes pruned and started another pod overnight and we had the same issue.

**Comment by rosskevin** [comment]
Thanks @arturictus - I'll work on gathering that information on the next incident which I expect will be soon.

> Do you know why kubernetes shutdown the pod?
It appears to me GKE did a node upgrade so transitioned sidekiq by starting a new pod and terminating the old.

We also see this triggered when we `kubectl delete -f app.yml` and end up redeploying.  We don't have our blue/green deployments running yet and are in alpha so we are still manually deploying and this happens every time.

@bmcdaniel11 will provide more information soon.

**Comment by bmcdaniel11** [comment]
Hi @arturictus, I have attached our shutdown to startup logs so I don't clutter up the conversation. The logs start from the latest alive workers executed before deleting our `app.yml` and stop where the sidekiq alive worker executes every few milliseconds (goes on for a few minutes). Please let me know how I can provide more information. 

[termination_logs.txt](https://github.com/arturictus/sidekiq_alive/files/2796943/termination_logs.txt)

**Comment by bmcdaniel11** [comment]
I just redeployed and it seems like the scaling down resolved the issue. The workers only executed the expected number of times. I'll keep monitoring it and let you know if I see it start happening.

**Comment by fruwe** [comment]
I switched today the gem from my PR https://github.com/arturictus/sidekiq_alive/pull/7 to the master branch. Within three hours 2 Million jobs where processed. (Note this is a cluster, which is currently not processing any jobs, except sidekiq alive)

<img width="558" alt="screen shot 2019-02-07 at 17 42 12" src="https://user-images.githubusercontent.com/71813/52399626-24dd7b80-2b00-11e9-8443-fa2d95577beb.png">

**Comment by fruwe** [comment]
I have two different deployments, which process different queues.
The high priority queue got stabilized about an hour ago as you can see here:

<img width="558" alt="high" src="https://user-images.githubusercontent.com/71813/52400080-72a6b380-2b01-11e9-9181-4814eba002fb.png">

**Comment by fruwe** [comment]
The high priority worker only has one pod. There are three other pods, which process all queues.
There was one pod which got restarted for some reason, since this one is the most interesting log, I attached the log (as pngs,,,sorry)

**Comment by fruwe** [comment]
<img width="1112" alt="low1" src="https://user-images.githubusercontent.com/71813/52400225-df21b280-2b01-11e9-9b58-b6f96749ff24.png">
<img width="887" alt="low2" src="https://user-images.githubusercontent.com/71813/52400223-df21b280-2b01-11e9-9fce-fd8c104113c8.png">
<img width="1111" alt="low3" src="https://user-images.githubusercontent.com/71813/52400222-de891c00-2b01-11e9-847b-98cbfe01a1eb.png">
<img width="1037" alt="low4" src="https://user-images.githubusercontent.com/71813/52400221-de891c00-2b01-11e9-98b3-6651309c9274.png">

**Comment by fruwe** [comment]
my kubernetes file looks mostly like this:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq-low
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xxx
      tier: sidekiq-low
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: xxx
        tier: sidekiq-low
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
            weight: 100
      terminationGracePeriodSeconds: 300
      containers:
      - name: sidekiq-low
        image: gcr.io/${GOOGLE_CLOUD_PROJECT}/xxx:${RELEASE_TAG}
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - |
            dumb-init -- bundle exec foreman start --env .env.foreman --formation "$FORMATION"
        ports:
          - containerPort: 7433
        livenessProbe:
          httpGet:
            path: /
            port: 7433
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 7433
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 15
        resources:
          requests:
            cpu: 10m
            memory: 400Mi
          limits:
            cpu: 300m
            memory: 700Mi
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: APP_ENV
            value: production
          - name: DATABASE_URL
            value: mysql2://...
          - name: FORMATION
            value: web=0,worker=1
          - name: RACK_ENV
            value: production
          - name: RAILS_ENV
            value: production
          - name: RAILS_MAX_THREADS
            value: "1"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: environment
                key: SECRET_KEY_BASE
          - name: SIDEKIQ_CONCURRENCY
            value: "2"
          - name: SIDEKIQ_QUEUES
            value: mailer,high,default,low,lowest
          - name: WEB_CONCURRENCY
            value: "1"
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["bundle", "exec", "sidekiqctl", "quiet", "tmp/pids/sidekiq.pid"]
```
