### ISSUE TITLE
Pods keep failing health check

### ISSUE THREAD

**Issue by i5okie** [arturictus/sidekiq_alive#35]
Hi,

I'm using :
sidekiq (5.2.7)
sidekiq_alive (2.0.1)

Deployment:
```yaml
spec:
      containers:
      - name: sidekiq
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["bin/bundle", "exec", "sidekiq"]
        args: ["-q", "critical", "-q", "notifications", "-q", "default", "-q", "low"]
        ports:
          - containerPort: 7433
          - containerPort: 9394
         livenessProbe:
           httpGet:
             path: /
             port: 7433
           initialDelaySeconds: 80 # app specific. Time your sidekiq takes to start processing.
           timeoutSeconds: 5 # can be much less
         readinessProbe:
           httpGet:
             path: /
             port: 7433
          initialDelaySeconds: 80 # app specific
          timeoutSeconds: 5 # can be much less
```
I have another deplyimg mirrors config above, except i'm specifying a different queue there.

it keeps failing the liveness or readiness probe every few minutes and reboots:
![image](https://user-images.githubusercontent.com/2119240/80009616-2afa1680-847e-11ea-8e9e-f18c7f61e689.png)

some are saying `Detected parent died, dying` others show nothing in logs that would indicate anything going wrong.
